# Get University Location Information from API

In [21]:
import pandas as pd
import requests
import json

## get university list

In [22]:
import numpy as np
University_Folder=np.genfromtxt('University_Folder.csv',delimiter=',',dtype='str')
University_Folder

array(['Carnegie_Mellon_University', 'New_York_University',
       'Ohio_State_University', 'Oregon_State_University',
       'Portland_State_University', 'Univeristy_of_Illinois_Champaign',
       'University_of_Arizona', 'University_of_California_Berkeley',
       'University_of_Colorado', 'University_of_Delaware',
       'University_of_Kentucky', 'University_of_Maryland_College_Park',
       'University_of_Mississippi', 'The_University_of_Texas_at_Austin',
       'University_of_Utah', 'University_of_Virginia',
       'University_of_Wisconsin_Madison', 'Carlow_University',
       'University_of_Pittsburgh', 'Duquesne_University',
       'Chatham_University', 'Cornell_University', 'Columbia_University',
       'Syracuse_University', 'Fordham_University', 'Pace_University',
       'University_of_Denver', 'Metropolitan_State_University_of_Denver',
       'Portland_State_University', 'University_of_Oregon',
       'Concordia_University', 'University_of_Kentucky',
       'University_of_Michigan_Ann_Arbor',
       'University_of_Maryland_College_Park', 'Lewis_&_Clark_College',
       'Texas_A&M_University_College_Station', 'University_of_Houston',
       'University_of_Illinois_at_Urbana_Champaign',
       'University_of_Illinois_at_Chicago', 'Northwestern_University',
       'San_Francisco_State_University',
       'University_of_Southern_California', 'Northern_Arizona_University',
       'Los_Angeles_City_College',
       'University_of_Washington_Seattle_Campus', 'Boston_University',
       'Northeastern_University', 'Georgia_State_University',
       'Emory_University', 'Richland_College', 'Universidad_Del_Turabo',
       'Georgia_Institute_of_Technology_Main_Campus',
       'University_of_California_Los_Angeles'], dtype='<U43')

## Request data from API and save them to seperate json files with the name of the universities
### This code will take a while to run

In [23]:
for university in University_Folder:
    result='%20'.join(university.replace('&','_').split('_'))
    response=requests.get('https://api.data.gov/ed/collegescorecard/v1/schools.json?api_key=evae9uBE9KLJd6IlRnqFyQ9rqJpYQxxAh39RYfkd&_fields=id,school.name,school.zip,school.state,school.city,location.lat,location.lon&school.name='+result)
    jdata=response.json()
    f = open(university+'.json', 'w')
    json.dump(jdata,f)

# Merge all the Json file to one csv file

## create multiple dataframe from json files

In [24]:
location_dict={}
for university in University_Folder[:-1]:
    d=json.load(open(university+'.json'))
    location_dict[university]=pd.DataFrame.from_dict(d['results'], orient='columns')

# merge the dataframes to one dataframe

In [25]:
data=pd.DataFrame()
for university in University_Folder[:-1]:
    data=data.append(location_dict[university],sort=False)
        
data

,id,location.lat,location.lon,school.city,school.name,school.state,school.zip
0,211440,40.443570,-79.941993,Pittsburgh,Carnegie Mellon University,PA,15213-3890
0,194310,40.711014,-74.004719,New York,Pace University-New York,NY,10038-1598
1,193900,40.729452,-73.997264,New York,New York University,NY,10012-1091
2,195809,40.722523,-73.796104,Queens,St John's University-New York,NY,11439
3,196176,41.740936,-74.082188,New Paltz,State University of New York at New Paltz,NY,12561-2443
4,190150,40.808286,-73.961885,New York,Columbia University in the City of New York,NY,10027
0,204705,40.069314,-82.447441,Newark,Ohio State University-Newark Campus,OH,43055
1,204671,40.738521,-84.023840,Lima,Ohio State University-Lima Campus,OH,45804
2,204680,40.796536,-82.580194,Mansfield,Ohio State University-Mansfield Campus,OH,44906
3,204699,40.577779,-83.090597,Marion,Ohio State University-Marion Campus,OH,43302-5695
4,204796,39.999324,-83.014853,Columbus,Ohio State University-Main Campus,OH,43210
5,204662,40.775194,-81.922936,Wooster,Ohio State University Agricultural Technical I...,OH,44691-4000
0,209542,44.563950,-123.274723,Corvallis,Oregon State University,OR,97331
1,440828,44.042795,-121.333703,Bend,Oregon State University-Cascades Campus,OR,97702
2,432241,45.424135,-122.745086,Tigard,University of Phoenix-Oregon,OR,97223-8328
3,209551,44.045146,-123.075792,Eugene,University of Oregon,OR,97403
0,209807,45.511601,-122.686289,Portland,Portland State University,OR,97201
1,208187,45.522130,-122.677741,Portland,Paul Mitchell the School-Portland,OR,97205
2,375841,45.520289,-122.681536,Portland,Le Cordon Bleu College of Culinary Arts-Portland,OR,97205-2793
0,487296,31.567832,-110.245117,Sierra Vista,University of Arizona-South,AZ,85635
1,484613,33.402130,-111.965987,Tempe,University of Phoenix-Arizona,AZ,85282
2,104179,32.232672,-110.950815,Tucson,University of Arizona,AZ,85721-0066
0,110635,37.871918,-122.260463,Berkeley,University of California-Berkeley,CA,94720
1,245342,38.721992,-90.311898,Berkeley,Vatterott College-Berkeley,MO,63134
2,125170,37.869769,-122.269877,Berkeley,Berkeley City College,CA,94704
3,183789,40.898587,-74.189483,Woodland Park,Berkeley College-Woodland Park,NJ,07424
4,189228,40.753986,-73.979458,New York,Berkeley College-New York,NY,10017
5,18922801,0.000000,0.000000,White Plains,Berkeley College - Westchester Campus,NY,10601
6,384306,37.862754,-122.267636,Berkeley,Acupuncture and Integrative Medicine College-B...,CA,94704
0,126580,38.892735,-104.800296,Colorado Springs,University of Colorado Colorado Springs,CO,80918
...,...,...,...,...,...,...,...
0,122597,37.721345,-122.477905,San Francisco,San Francisco State University,CA,94132
1,486372,37.791643,-122.401124,San Francisco,San Francisco Film School,CA,94104-2835
2,122454,37.803575,-122.417000,San Francisco,San Francisco Art Institute,CA,94133-2299
0,123961,34.021281,-118.284169,Los Angeles,University of Southern California,CA,90089
1,123651,33.662686,-117.900911,Costa Mesa,Vanguard University of Southern California,CA,92626
2,117672,33.922966,-117.983401,Whittier,Southern California University of Health Sciences,CA,90604
0,105330,35.188449,-111.653724,Flagstaff,Northern Arizona University,AZ,86011-4092
0,117788,34.087301,-118.292169,Los Angeles,Los Angeles City College,CA,90029
0,236948,47.655380,-122.305140,Seattle,University of Washington-Seattle Campus,WA,98195-4550
0,164988,42.351118,-71.107942,Boston,Boston University,MA,02215
1,166638,42.312881,-71.036865,Boston,University of Massachusetts-Boston,MA,02125-3393
0,167358,42.339992,-71.088782,Boston,Northeastern University,MA,02115-5005
1,147776,41.980399,-87.718983,Chicago,Northeastern Illinois University,IL,60625-4699
2,207263,35.919939,-94.967229,Tahlequah,Northeastern State University,OK,74464-2399
3,107327,35.898597,-89.921005,Blytheville,Arkansas Northeastern College,AR,72316-1109
4,482705,42.339477,-71.087841,Boston,Northeastern University Professional Advanceme...,MA,02115
5,207290,36.877255,-94.867248,Miami,Northeastern Oklahoma A&M College,OK,74354
0,139940,33.752700,-84.386670,Atlanta,Georgia State University,GA,30303-3083
1,482158,32.808092,-83.732058,Macon,Middle Georgia State University,GA,31206
2,139764,32.054662,-84.217738,Americus,Georgia Southwestern State University,GA,31709-4693
3,244437,33.753426,-84.385712,Atlanta,Georgia State University-Perimeter College,GA,30303-3083
4,139861,33.082787,-83.231962,Milledgeville,Georgia College & State University,GA,31061
0,139658,33.790183,-84.325512,Atlanta,Emory University,GA,30322
1,487092,33.619100,-83.871141,Oxford,Emory University-Oxford College,GA,30054
2,232025,36.772857,-81.829142,Emory,Emory & Henry College,VA,24327-0947
0,227766,32.922141,-96.730505,Dallas,Richland College,TX,75243-2199
1,148292,39.883887,-88.894125,Decatur,Richland Community College,IL,62521-8512
2,234924,46.226260,-119.246059,Richland,Paul Mitchell the School-Richland,WA,99352
0,243601,18.239647,-66.006259,Gurabo,Universidad del Turabo,PR,00778-3030
0,139755,33.772420,-84.394832,Atlanta,Georgia Institute of Technology-Main Campus,GA,30332-0530

# Save the dataframe to csv

In [26]:
data.to_csv('university_location.csv',sep=',')